nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: This api can give you access to all the cellphone in the **world**! and centralize your client and your products
            version: 1.0.0
        security:
            - Bearer: [ ]
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                Login:
                    type: object
                    properties:
                        username:
                            type: string
                            description: the username you use to connect
                        password:
                            type: string
                            description: you know what a password is right ?
                Error:
                    type: object
                    properties:
                        code:
                            type: string
                        message:
                            type: string
                    required:
                        - code
                        - message
            responses:
                NotFound:
                    description: The specified resource was not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                Server:
                    description: there has been an error in our server
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                Unauthorized:
                    description: you do not have the authorization to access this ressource
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'


        paths:
            Errors:
                get:
                    tags:
                        - Errors
                    summary: The Error Response you could expect
                    description:
                        list the different error type you could have using our api
                    responses:
                        '404':
                            $ref: '#/components/responses/NotFound'
                        '401':
                            $ref: '#/components/responses/Unauthorized'
                        '500':
                            $ref: '#components/responses/Server'
            /api/login_check:
                post:
                    tags:
                        - Login
                    summary: Get the Bearer Token
                    description: >
                        Use this link to authenticate yourself to the database and test the paths
                        You'll need your **username** and your **password**.
                    operationId: LoginClient
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    ref: '#components/schemas/Login'

                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        properties:
                                            token:
                                                type: string

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        names:
            - { alias: Product Details,        type: App\Entity\Product, groups: [productDetails] }
            - { alias: Product Summary, type: App\Entity\Product, groups:[productList]}
            - { alias: User Details, type: App\Entity\User, groups:[userDetails]}
            - { alias: User Summary, type: App\Entity\User, groups:[userList]}
